### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor when running review --fix

### ISSUE THREAD

**Issue by rob101** [sourcery-ai/sourcery#378] opened 2023-08-19 23:39 UTC
### Checklist

- [x] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing.
- [x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem.

### Description
When I try to run Sourcery, I get an `OSError: [Errno 9] Bad file descriptor`. This error occurs when the tool attempts to write to a file. I expected the program to run without any file-related errors.

### Code snippet that reproduces issue
N/A (The issue is not directly related to a specific piece of Python code.)

```python
C:\Users\[user]\Documents\GitHub\[project]\.venv\Scripts\sourcery.exe review --fix C:\Users\[user]\Documents\GitHub\[project]\src
```

### Debug Information
- **OS**: (e.g., Windows 11)
- **Python Version**: 3.10.11
- **Sourcery Version**: Latest
- **Traceback**: 
```
Traceback (most recent call last):
  File "C:\Users\[user]\DOCUME~1\GitHub\[project]\VENV~1\Lib\SITE-P~1\sourcery\__main__.py", line 430, in <module>
...
OSError: [Errno 9] Bad file descriptor
```

**Comment by bm424** [comment] 2023-08-21 09:34
Hi @rob101, thanks for reporting this. I'll take a look later this week.

**Comment by bm424** [comment] 2023-08-22 15:22
Hi @rob101, I've checked this over and there doesn't appear to be a general bug with `sourcery review --fix` or writing to files in our binary. I suspect the problem is specific to your system (maybe file permissions?). I'm closing this issue for now, but please do send an email to support@sourcery.ai and we can try to troubleshoot.

**Closed by bm424** 2023-08-22 15:22 UTC
Labels: bug
