### ISSUE TITLE
instance-method-first-arg-name triggers on unrelated global funcs

### ISSUE THREAD

**Issue by amogorkon** [sourcery-ai/sourcery#328] opened 2023-03-28 13:30 UTC
### Checklist

- [x] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description
In some cases when a global function follows a class with methods, sourcery suggests to add `self` to the arg or change the first parameter to "self", although it's not a method. I attached a screenshot with the issue.

### Code snippet that reproduces issue
![Unbenannt](https://user-images.githubusercontent.com/16521496/228252763-16b8745d-c0b6-4e43-b202-1507db5d549f.PNG)

```
class Test:
    def __init__(self, bla):
        self.bla = bla
    def foo(self):
        print("foo")
    def bar(self):
        print("bar")


def bar(bla):
    print(bla.bla)
```

### Debug Information

IDE Version: 
Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Datum: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
Betriebssystem: Windows_NT x64 10.0.19045
Sandkasten: No

Sourcery Version: 
v1.0.9

Operating system and Version:
Windows 10

**Comment by wardy3** [comment] 2023-09-21 04:24
> Which IDE are you using? Does Sourcery also show this suggestion with `self` when you run `sourcery review` in the CLI?

I'm also using VSCode and get the same issue. It must be related to previous code, as I copied my class and the global function below it into a new file but the error is now gone.

It does not occur if I use `sourcery review mydir` where the file resides

**Comment by bm424** [comment] 2023-10-16 13:55
I've had another look at this and I can't reproduce it. If someone has a complete `.py` file they could share and some process they've found that reliably creates the refactoring in the wrong place, we have a shot at solving this.

**Comment by Estrangeling** [comment] 2023-10-16 17:08
This is a bit more complicated example, I have defined a function first, and added a dummy class before it, the function has its parameters annotated, but the bug still triggers. This would rule out that annotations are related in anyway.

```
class Dummy:
    def __init__(self):
        pass

def power(base: float, exp: int):
    if not exp:
        return 1.0

    if exp < 0:
        base = 1 / base
        exp = -exp

    p = 1.0
    while exp:
        if exp & 1:
            p = base * p

        base *= base
        exp >>= 1

    return p
```

![2023-10-17_010641](https://github.com/sourcery-ai/sourcery/assets/78679218/db64c5e8-f5bf-4432-ba47-634abbdb6d97)

Closing the editor and reopening it, the bug goes away.

**Comment by bm424** [comment] 2023-10-17 08:48
Thanks @Estrangeling, with that I've been able to reproduce and track it down. There are two issues working in tandem here: first, the refactoring is triggered specifically when this code is written (note the syntax error)
```python
class Example:
    def
def something(a):
    ...
```
So something about the parser is misattributing the function when it sees this syntax error.

The second problem is that we cache refactorings to avoid re-computing them, and in this case the cached refactoring persists until you restart the IDE. 

Thanks for your help, and I'll take a look at this today - look out for a fix in the next release.

**Comment by bm424** [comment] 2023-10-19 09:44
A quick update - I'm still working on this (turns out to be quite a low-level bug) so unfortunately it didn't make it into yesterday's release.

**Closed** 2023-10-20 08:42 UTC
Labels: bug
