### ISSUE TITLE
Refactor moves part of code out of loop changing the meaning of the code

### ISSUE THREAD

**Issue by marcoaaguiar** [sourcery-ai/sourcery#87] opened 2020-10-17 15:02 UTC
### Issue description or question
Related to #85, but not exactly the same since it doesn't refactor to invalid code.

The issue that I'm having is that the refactor changes the meaning of the code.

Original code
```python
from math import inf


def solve(self):
    node_error = {}
    max_error = inf

    for it in range(self["max_iter_outer"]):
        print(it)
        # update nu
        for node in self["network"]:
            node_error[node] = __import__("random").random()

        # error  # << This line is marked to refactor
        max_error = max(node_error.values())
        if max_error < self["abs_tol"]:
            print("{}".format(max_error))
            break

    return None


solve({"max_iter_outer": 10, "network": {"node1": 10, "node2": 20}, "abs_tol": 0.45})
```

Refactors to
```python
from math import inf


def solve(self):
    node_error = {}
    max_error = inf

    # error
    max_error = max(node_error.values())  # << Moved to here
    for it in range(self["max_iter_outer"]):
        print(it)
        # update nu
        for node in self["network"]:
            node_error[node] = __import__("random").random()

        if max_error < self["abs_tol"]:
            print("{}".format(max_error))
            break

    return None

solve({"max_iter_outer": 10, "network": {"node1": 10, "node2": 20}, "abs_tol": 0.45})
```

If you judge that is the same as #85 feel free to close this issue and move the example to there.

BTW I would be nice if the line marked was the actual line of code was marked. Alternatively both lines could be marked, since both are moving. 

Also, if I remove the print statement it will complaint about the assigned loop variable `it` (which is correct). However it will bundle the "replace unused for index with underscore" with the "hoist statement out of loop", which reduces the control by the user.

### Sourcery Version
0.8.0

### Code editor or IDE name and version

Discovered on NeoVim 0.5.0, but confirmed on VSCode

### OS name and version

Ubuntu 20.04 via WSL

**Comment by Hellebore** [comment] 2020-10-19 15:07
Yeah this is a duplicate of #85, and I've checked that this example is also fixed.

Improving the highlighting and unbundling the suggestions where possible is on our long-term roadmap.

**Closed by Hellebore** 2020-10-19 15:07 UTC
Labels: bug
