### ISSUE TITLE
How do I get rid of "Sourcery Code Metrics"?

### ISSUE THREAD

**Issue by Predeactor** [sourcery-ai/sourcery#282] opened 2022-09-17 21:53 UTC
Hi, I'm a user of VSCode & Sourcery, and I very often read the comments of methods.

I am very annoyed by the "Sourcery Code Metrics" because this is irrelevant to me and sometime is buggy.
![image](https://user-images.githubusercontent.com/61093863/190877543-25190ec6-cf62-4f95-a4e6-74b5e6666b32.png)

How do I remove it? There's no option in settings and I don't want it anywhere.
Thank

**Comment by Hellebore** [comment] 2022-09-18 08:21
Hi @Predeactor - thanks for getting in touch.

You can turn these off permanently by adding a setting to your user `sourcery.yaml` file.
The file containing the setting would look like this:
```
refactor:
  skip:
  - function-quality
```
  
  The location of this file is platform-dependent - you can find details here:
  https://docs.sourcery.ai/Reference/Configuration/Sources/

**Comment by Predeactor** [comment] 2022-09-18 08:31
This does not seem to work
Just to be sure, I've created a `sourcery.yaml` and `.sourcery.yaml` but there is no change.

Do you have anything else perhaps?

**Comment by Hellebore** [comment] 2022-09-18 08:53
Hi @Predeactor that's strange - could you post the file, its location and your OS, and make sure you've restarted VS Code?

One shortcut to making this work is also to take the 'Never show me this refactoring' option on a different refactoring and then edit the file it creates by changing the refactoring id.

**Comment by Predeactor** [comment] 2022-09-18 09:16
Hey,
I won't answer your question yet because, to my surprise, Sourcery does not work at all now! So no point trying to fix one thing if the whole thing doesn't work. There's just no suggestion at all...
![image](https://user-images.githubusercontent.com/61093863/190894814-1bfb654a-4b9f-445c-ac4f-f77e5e26fdb1.png)

I deleted the folder `%AppData%/sourcery` and rebooted VSC. Nothing change, no suggestion...
And I am not working in a workspace, there's only this file opened

I'm quite stuck now... 😅

**Comment by Hellebore** [comment] 2022-09-18 10:43
Oh no! Some questions:

1. When did this start - was it after taking the 'never show me this refactoring' option?
2. Are any error notifications shown when you start VS Code?
Also could you possibly find your log file and mail it to support@sourcery.ai? That will help me diagnose the issue.

https://docs.sourcery.ai/Product/Troubleshooting/

**Comment by Predeactor** [comment] 2022-09-18 10:48
1. This has started after using your suggestion/creating a global `sourcery.yaml` apparently
2. VSC has (Finally? I never had it since now) a notification:
    > 'charmap' codec can't encode character '\U0001fa84' in position 2: character maps to <undefined> - Source: Sourcery (Extension)

I have sent you my log file in the given address!

**Comment by Hellebore** [comment] 2022-09-18 11:09
Hmm - is there a sourcery folder in %LOCALAPPDATA% ? 
If so then could you post the contents of any sourcery.yaml file in there and then try removing it?

**Comment by Predeactor** [comment] 2022-09-18 11:14
`%LocalAppData%/sourcery/sourcery.yaml` exist... I know where this is getting x)

Content: 
```yml
refactor:
  rule_types: []
```

Deleted and... Oh, it works once again!
I tried to re-add the content of `sourcery.yaml` from the beginning and surprisingly, there's no refactor again... The `%LocalAppData/sourcery/sourcery.yaml` kicks-in again with the same content as above
Guess it shouldn't happens?

**Comment by Predeactor** [comment] 2022-09-18 11:20
I added:
```yml
refactor:
  skip:
  - function-quality
``` to `%LocalAppData/sourcery/sourcery.yaml`, and this time, it works just fine! The "Sourcery Code Metrics" is no more and Sourcery work just fine!

Should I keep this issue open so you can keep track of what happened today?

**Comment by Hellebore** [comment] 2022-09-18 11:27
Yes - let's leave it open since it looks like there definitely might be some weird behaviour to investigate.

Really glad you got it working!

**Comment by brendanator** [comment] 2022-09-20 07:34
This configuration will stop Sourcery basically doing anything
```yaml
refactor:
  rule_types: []
```
as it is saying don't try any rule types.

The default config for this setting is:
```yaml
refactor:
  rule_types:
  - refactoring
  - suggestion
  - comment
```
which enables all types of rule.

@Predeactor Do you know how your config got into this state?

**Comment by Predeactor** [comment] 2022-09-20 09:48
@brendanator The only thing I've done to achieve this state is to put the following into `%AppData%/sourcery/sourcery.yaml`:

```yaml
refactor:
  skip:
  - function-quality
```

I guess that's because I do not specific rules in this file? 😛

**Comment by brendanator** [comment] 2022-09-23 15:35
I looks like there's three issues here:
- our docs show the config location as `%appdata%` when sourcery has put it in `%localappdata%`
    - This is fixed in the next release - Sourcery will put the config in the right place
- charmap' codec can't encode character '\U0001fa84 
    - duplicate of https://github.com/sourcery-ai/sourcery-vscode/issues/89
    - fixed in the next release
- `rule_types: []` appeared in your config file 
    - Do you know how this happened? Did you try clicking VSCode options to disable `refactorings`, `suggestions` and `comments` to switch off Sourcery metrics?

**Comment by Predeactor** [comment] 2022-09-23 18:39
> * @Predeactor Do you know how this happened? Did you try clicking VSCode options to disable `refactorings`, `suggestions` and `comments` to switch off Sourcery metrics?

Yes, all these settings were disabled actually
![image](https://user-images.githubusercontent.com/61093863/192035017-ed5520c9-3a8d-4628-94f9-5f3e77c94f71.png)
I actually am wondering if they had any effects actually, I feel like it was still working as expected before I try touching the `sourcery.yaml` file manually.

**Comment by brendanator** [comment] 2022-09-26 15:36
Thanks @Predeactor, let's assume that this emptied the `rule_types` then. Once the other two issues are completed I'll close this

Thanks for your detailed report and all your help 🙏

**Comment by Hellebore** [comment] 2022-10-14 14:12
Made the fixes - now live.

**Closed by Hellebore** 2022-10-14 14:12 UTC
Labels: bug, question, next release

**Comment by wy6688** [comment] 2024-06-22 23:39
how to permanently disable or remove Sourcery.ai? it's very annoy I cannot disable this modules, just feel be kidnaped by it, just malious software .
