### ISSUE TITLE
Sourcery failed to Launch Error: RecordCollection contained more than one row...

### ISSUE THREAD

**Issue by seanmb0** [sourcery-ai/sourcery#55] opened 2020-06-06 03:40 UTC
### Issue description or question
Sourcery Plugin fails to launch in PyCharm IDE.  After upgrading to PyCharm 2020.1 from 2019.3 Sourcery fails to load. 

Error message in Event Log:
6:20 PM Failed to launch Sourcery service: RecordCollection contained more than one row. Expects only one row when using RecordCollection.one

I have tried completely uninstalling and reinstalling PyCharm 2020.1; uninstalling and installing 2019.3 : on both I only installed the Sourcery Plugin.  In all cases I get the exact same error.

Any idea of where this RecordCollection.one is stored and how I can fix this?

### Sourcery Version
Sourcery 0.3.7

### Code editor or IDE name and version

> PyCharm 2020.1.1 (Professional Edition)
> Build #PY-201.7223.92, built on April 29, 2020
> Licensed to -snip-
> Subscription is active until February -snip-
> Runtime version: 11.0.6+8-b765.40 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1998M
> Cores: 4
> Non-Bundled Plugins: sourcery.pycharm-plugin

### OS name and version
Windows 10 Version 1909 (OS Build 18363.836)

**Comment by brendanator** [comment] 2020-06-06 09:11
Apologies about this, I thought I had managed to fix this issue a little while ago but clearly not.

You can resolve the issue by deleting the local Sourcery database. On Windows this should be in `%LOCALAPPDATA%/sourcery`, (or `%APPDATA%/sourcery` if the first doesn't exist).

To help me track down the route cause of the issue, could you let me know if this was caused by updating the Sourcery plugin or if it happened immediately after you installed it?

**Comment by seanmb0** [comment] 2020-06-06 20:56
Great! That worked. 

I first installed Sourcery 0.3.5 in PyCharm 2019.3.? around 5/7/20 and was using it successfully. I then upgrade both Sourcery and PyCharm on 5/22  to versions 0.3.5 and 2020.1.1, after this Sourcery would not load.  

I have another question on licencing. 
When I first loaded the plug-in I do not recall seeing the restriction to open source for the free tier, and that. IIRC, access to 'Advanced Refactoring' was to be difference between Free and Pro pricing tiers. Now it looks like that after the beta period, IDE integration will require the 'Pro' licencing. I use Python as job aid and while the code is not my job output, the code it is not open source. 

- Am I required to purchase a 'Pro' License now or do I wait until the end of beta?
- And if now, where do I pay? 

I always try to stay on the right side of any license agreement.

**Comment by brendanator** [comment] 2020-06-07 11:49
Great, and thanks for the information.

We've updated our pricing page recently but the vast majority of the information on there actually refers to the GitHub Bot which we've more recently launched. If you want to use the bot for non-open source then you'll need a Pro license. However you can carry on using the plugin on any codebase you like. If we ever changed this we would grandfather all our existing users in. In summary, you are perfectly within the license agreement.

**Comment by Hellebore** [comment] 2020-07-01 09:56
Should be resolved with PyCharm plugin version 0.5.0

**Closed by Hellebore** 2020-07-01 09:56 UTC
Labels: bug
