### ISSUE TITLE
raise 'instance-method-first-arg-name' by mistake on inner functions

### ISSUE THREAD

**Issue by makpia** [sourcery-ai/sourcery#370] opened 2023-07-22 13:02 UTC
### Checklist

- [y] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [y] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description

if
- using 'if else' in a default value of an instance method paramter declaration
- the parameter name is in a new line

then all functions defined inside the method will be treated as instance method by mistake, so sourcery will check if the first parameter name is 'self'

in the following code example, sourcery reports 'instance-method-first-arg-name' error on function 'inner_func' 

### Code snippet that reproduces issue

```python
from typing import Callable


class C:
    def f(self,
        func: Callable[[int], int] = lambda x: x if x > 1 else 0
    ) -> None:
        def inner_func(a: int) -> int:
            return a
        return 
```

### Debug Information

IDE Version: 

vs code 1.80.0

Sourcery Version: 

1.6.0

Operating system and Version:

windows 11

**Comment by Hellebore** [comment] 2023-07-28 13:56
Thanks for raising this - have reproduced it

**Comment by ruancomelli** [comment] 2024-01-08 20:52
Hello, @makpia!

I believe this has been fixed with recent changes in how we analyze nested functions. Can you please upgrade Sourcery to the latest version (v1.15.0) and test this again?

**Comment by ruancomelli** [comment] 2024-01-15 11:16
Closing this issue since this issue was fixed in the latest Sourcery releases - please reopen it in case it happens again for you :smile:

**Closed by ruancomelli** 2024-01-15 11:16 UTC
Labels: bug
