### ISSUE TITLE
sourcery review --fix does not work on directories.

### ISSUE THREAD

**Issue by rob101** [sourcery-ai/sourcery#384] opened 2023-08-29 09:57 UTC
### Checklist

- [x ] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [ x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description
When running sourcery review -fix [dirname] sourcery will identify the number of files but fail to lint or provide any fixes.

When running sourcery review -fix [filename] it applies fixes as expected.

### Debug Information

IDE Version: 
Terminal

Sourcery Version: 
Latest

Operating system and Version:
Windows 11

**Comment by ruancomelli** [comment] 2023-08-29 14:42
Hello, @rob101! Thanks for reaching out.

Unfortunately, I am unable to reproduce this issue. The command `sourcery review --fix [path]` works correctly even if `path` is a directory (I tested it with the `sourcery --version` `1.8.0`).

Can you please share your [Sourcery log file](https://docs.sourcery.ai/Product/Troubleshooting/#what-is-the-sourcery-log) with support@sourcery.ai for me to further look into this issue?

**Comment by Hellebore** [comment] 2023-09-15 15:19
Closing for now - please reopen if we get more details

**Closed by Hellebore** 2023-09-15 15:19 UTC
Labels: bug
