### ISSUE TITLE
Failed to launch Sourcery service

### ISSUE THREAD

**Issue by glllom** [sourcery-ai/sourcery#200] opened 2022-02-28 11:01 UTC
Hi. I've got this issue:
Failed to launch Sourcery service: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed

Sourcery Version - 0.10.3

Often available in Sourcery settings - default

PyCharm 2021.3.2 (Professional Edition)

Operating System: Manjaro Linux
KDE Plasma Version: 5.24.2
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.15.21-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i3-6100 CPU @ 3.70GHz
Memory: 15.6 GiB of RAM

**Comment by bm424** [comment] 2022-02-28 17:50
Hi @glllom, thank you for opening this issue. It looks fairly likely that Sourcery isn't compatible with your operating system. However, I'm investigating further and I'll try to see if there's anything we can do to fix this.

**Comment by glllom** [comment] 2022-02-28 18:28
Hi, Ben. Thank you for your response. Actually it did work until now for
several months. A few days ago I crashed my system and reinstalled it
(clean install). Perhaps, it was an older version of manjaro. Whatever, it
was enough modern. I assume that there is poor chance that the problem is
in the operating system.

пн, 28 февр. 2022 г. в 19:50, Ben Martineau ***@***.***>:

**Comment by javierriveracastro** [comment] 2022-03-07 12:04
This is a likely a duplicate of #196 (exactly the same problem but in Arch), the workaround that I posted there will probably also work on Manjaro.

**Comment by ruancomelli** [comment] 2022-03-09 19:17
@glllom can you try the solution proposed in #196 to see if it works? It should be as simple as running:
```
pacman -S libxcrypt-compat
```

**Comment by glllom** [comment] 2022-03-10 06:53
Ok. It is fixed now. Thank you very much! Your support is awesome.

ср, 9 мар. 2022 г. в 21:18, Ruan Comelli ***@***.***>:

**Comment by ruancomelli** [comment] 2022-03-10 12:40
It's great to hear that, thank you!
I'll close this thread in favor of #196 where we'll post further updates about this error.
Please let us know if you ever have any other issues!

**Closed by ruancomelli** 2022-03-10 12:40 UTC
Labels: bug
