### ISSUE TITLE
Refactoring `simplify-fstring-formatting` replaces newlines with `\x1f` in multiline strings

### ISSUE THREAD

**Issue by ruancomelli** [sourcery-ai/sourcery#240] opened 2022-05-20 12:55 UTC
### Issue description or question

The `simplify-fstring-formatting` refactoring is replacing newlines with the `\x1f` character in multiline strings. For instance,
```python
def ooops():
    return f"""
        Sourcery is
        {f"{'awesome'.upper()}"}
    """
```
is refactored as
```python
def ooops():
    return f"""\x1f        Sourcery is\x1f        {'awesome'.upper()}\x1f    """
```

The expected result would be
```python
def ooops():
    return f"""
        Sourcery is
        {'awesome'.upper()}
    """
```

### Sourcery Version

v0.11.5

### Code editor or IDE name and version

VS Code 1.67.2

### OS name and version

Ubuntu 20.04.4 LTS

**Comment by bm424** [comment] 2022-06-13 10:01
Duplicate of https://github.com/sourcery-ai/core/issues/1492

**Comment by Hellebore** [comment] 2022-06-21 09:25
Addressed with release of 0.12.1

**Closed by Hellebore** 2022-06-21 09:25 UTC
Labels: bug
