### ISSUE TITLE
Find intermediate variable

### ISSUE THREAD

**Issue by pzelnip** [sourcery-ai/sourcery#127] opened 2021-04-01 21:47 UTC
### Issue description or question

Not sure how to describe this, but I had this snippet in a function:

```
def my_function(items):
    result = []
    for i, item in enumerate(items):
        r = process_item(item)
        result.append(r)
    return result
```

I was surprised to see that Sourcery didn't recognize that the `r` variable could be entirely removed:

```
def my_function(items):
    result = []
    for i, item in enumerate(items):
        result.append(process_item(item))
    return result
```

And then if that refactoring is applied, the list comprehension refactoring would kick in:

```
def my_function(items):
    result = [process_item(item) for for i, item in enumerate(items)]
    return result
```

And then I'd expect it to realize that result is unneeded:

```
def my_function(items):
    return [process_item(item) for for i, item in enumerate(items)]
```

It looks like if I remove the intermediate assignment to `r` then Sourcery figures the rest out, but the intermediate assignment is being missed.

### Sourcery Version

Whatever version comes with the VS Code extension (v0.8.8)

### Code editor or IDE name and version

VS Code Version: 1.55.0

### OS name and version

OSX (OS: Darwin x64 19.6.0)

**Comment by Hellebore** [comment] 2021-04-02 20:37
Great idea, which I intend to add in the next few weeks. 

Closing this as it's a duplicate of https://github.com/sourcery-ai/sourcery/issues/84

**Closed by Hellebore** 2021-04-02 20:37 UTC
