### ISSUE TITLE
Sourcery does not recognizes docstrings

### ISSUE THREAD

**Issue by psstpakGithub** [sourcery-ai/sourcery#256] opened 2022-07-18 09:59 UTC
### Sourcery fails to recognize [python docstrings](https://peps.python.org/pep-0257/), and  the refactoring it offers delete the entire class/function

the "problem" it reports is
Sourcery - Remove unnecessary call to `str()` within `print()` (removes comment)

### Code editor or IDE name and version

Python 3.9 in VS Code

### OS name and version

Windows 10 21H2

**Comment by bm424** [comment] 2022-07-18 11:02
Hi @psstpakGithub, thanks for reporting. I can't easily reproduce the issue - Sourcery is correctly preserving docstrings in the example below. If possible, can you share an example of the code Sourcery is breaking on?

```python
class HatPicker(Picker):
    """Interface for picking hats."""

    def pick_hat(self, available_hats: Dict[Label, Hat]):
        """Gets your favourite hat from the list of available hats."""

        if self.favourite_hat in available_hats:
            hat_to_wear = available_hats[self.favourite_hat]
        else:
            hat_to_wear = NO_HAT
        return hat_to_wear
# becomes
class HatPicker(Picker):
    """Interface for picking hats."""

    def pick_hat(self, available_hats: Dict[Label, Hat]):
        """Gets your favourite hat from the list of available hats."""

        return available_hats.get(self.favourite_hat, NO_HAT)
```

**Comment by Hellebore** [comment] 2022-08-15 07:51
Hi @psstpakGithub  - will close this as we can't reproduce it. Please do re-open it with a code example and we'll work to resolve it.

**Closed by Hellebore** 2022-08-15 07:51 UTC
Labels: question
