### ISSUE TITLE
Clone detection not working in PyCharm Pro when scan includes venv folder

### ISSUE THREAD

**Issue by dancergraham** [sourcery-ai/sourcery#184] opened 2022-01-17 09:54 UTC
### Issue description or question

If I first select a whole directory in the PyCharm project view, right click and select Sourcery - Detect clones and then try to select a single .py file or multiple .py files then the following message is shown in the event window:

`Clone detection complete: Found 0 clones in 0 files.`

And `No clones found.` in the Sourcery window

### Steps to reproduce
- Open PyCharm
- Wait for Sourcery plugin to load
- Right click on project root folder -->  `Sourcery - Detect clones`
- Right click on any python file -->  `Sourcery - Detect clones`
Expected result : Sourcery scans for clones
Observed Result : nothing or message `Clone detection complete: Found 0 clones in 0 files.`

### Sourcery Version

Sourcery pro. Plugin version 0.9.8 Sourcery version 0.9.8

### Code editor or IDE name and version

PyCharm 2021.3.1 (Professional Edition)
Build #PY-213.6461.77, built on December 28, 2021

### OS name and version

Windows 10

**Comment by GrahamKnappAcernis** [comment] 2022-01-17 09:58
I have restarted PyCharm and cannot reproduce this - it now seems to be working correctly

**Comment by Hellebore** [comment] 2022-01-17 22:11
Thanks for reporting this - does this also occur with version 0.10.0 which has released in the last few days?

**Comment by GrahamKnappAcernis** [comment] 2022-01-18 08:49
Hello, yes I have just updated and repeated these steps with the same result. I get no output at all in the event window.
Two lines appear in the sourcery.log file when I run sourcery on the root directory and no lines are added to the log file on subsequent runs.  There are spaces in my file path.
Graham

**Comment by GrahamKnappAcernis** [comment] 2022-01-18 08:52
3 minutes later I get a traceback in the log file - I can share this in a private email if you would like

**Comment by Hellebore** [comment] 2022-01-18 10:36
That would be awesome thanks - could you send it over to support@sourcery.ai

**Comment by Hellebore** [comment] 2022-01-19 14:59
Thanks for the logs - looks like we're crashing when trying to parse the files to detect the clones. Would it be possible for you to email over a Python file for which it fails so we can reproduce it?

**Comment by GrahamKnappAcernis** [comment] 2022-01-20 10:42
Hello,
I think it may be because my venv is in the project folder – I have just successfully run Sourcery on every subfolder except venv.  Running it on venv it seems to hang…

**Comment by bm424** [comment] 2022-03-01 12:10
Hi @GrahamKnappAcernis I was able to reproduce your issue, and it seems to be as you suspected - Sourcery is trying to detect clones in every Python file in your `venv` folder. I suggest you add a `.sourcery.yaml` config file to your project's root directory, with the following contents:
```yaml
ignore:
  - venv
```
This will tell Sourcery to ignore the `venv` directory and all its subdirectories when performing bulk operations. You can find documentation about this feature [here](https://docs.sourcery.ai/Configuration/). Hope this helps!

**Closed** 2022-06-13 10:07 UTC
Labels: bug, low priority
