### ISSUE TITLE
Sourcery excessive memory/CPU consumption

### ISSUE THREAD

**Issue by gotdang** [sourcery-ai/sourcery#60] opened 2020-06-30 12:15 UTC
### Issue description or question
I'm using a MacBook Air with only 4GB RAM. When everything got sluggish, I looked at memory usage, and the sourcery process had almost 9GB allocated. When I disabled it in VSCode, it still was using the memory. Even after I exited VSCode, the sourcery process was still running. I felt like the sourcerer's apprentice, being overwhelmed by mops! I had to kill it from the command line.

### Sourcery Version

0.3.0

### Code editor or IDE name and version

VSCode 1.46.1

### OS name and version

OSX 10.15.5 "Catalina"

### Screenshot
![image](https://user-images.githubusercontent.com/8418541/86124641-78f84f80-baa9-11ea-98c4-755440584b58.png)

**Comment by Hellebore** [comment] 2020-06-30 12:27
Oh dear! Sorry about that - definitely a bug.

Can you remember if there were any particular actions you were doing before the spike in memory usage? Might help us to track it down.

**Comment by br3ndonland** [comment] 2020-07-07 16:09
I had a similar issue yesterday, same application environment (Sourcery Version 0.3.0, Code editor or IDE name and version VSCode 1.46.1, OS name and version OSX 10.15.5 "Catalina").

If I remember correctly, I had the Git diff for a Python module open in VSCode shortly before it happened. The earlier commit in the diff had the un-refactored code (and I did see the Sourcery hint pop up), and the later commit being compared in the diff had the code fixed by Sourcery. I'll try to open the VSCode dev tools next time to keep tabs on it.

**Comment by RhetTbull** [comment] 2020-07-13 06:23
Similar issue here.  I see this both on MacOS 10.13.6 and MacOS 10.15.5

- MacOS: 10.15.5
- Visual Studio Code: Version: 1.47.0
- Sourcery: 0.3.0

MacOS 10.15.5 screenshots:

<img width="1140" alt="Screenshot 2020-07-12 23 11 45" src="https://user-images.githubusercontent.com/41546558/87276752-d6bb6d00-c495-11ea-9607-001aad4f3b42.png">

<img width="963" alt="Screenshot 2020-07-12 23 11 23" src="https://user-images.githubusercontent.com/41546558/87276782-e89d1000-c495-11ea-8822-b3b2c6e3b36a.png">

MacOS 10.13.6 screenshots:
<img width="749" alt="Screen Shot 2020-07-12 at 6 59 25 PM" src="https://user-images.githubusercontent.com/41546558/87276947-3580e680-c496-11ea-984d-229fdb0d49a7.png">

<img width="754" alt="Screen Shot 2020-07-12 at 6 55 41 PM" src="https://user-images.githubusercontent.com/41546558/87276967-403b7b80-c496-11ea-8dd9-6a965b2ff2e2.png">

I was editing python code at the time.  I do frequently use the "Format code" with `black` command in VS Code which causes source files to change a lot but otherwise doing nothing unusual.

**Comment by brendanator** [comment] 2020-07-15 15:37
We've released a new version of Sourcery for VSCode - version 0.7.5. We've made several improvements in this area:
- Data structures optimized to decrease memory usage
- Added timeouts on refactorings so it won't run forever eating memory and CPU
- Added logic to cancel running refactorings on outdated versions of files

In our testing this seems to have solved it for us so I'll close the issue. Please comment if you're still having a problem

**Comment by RhetTbull** [comment] 2020-07-18 18:06
Definitely fixes it for me -- sourcery using 0% CPU and 100MB RAM!  Thanks!

**Comment by gotdang** [comment] 2020-08-03 13:42
Fixed for me, too. Thank you!

**Comment by AAraKKe** [comment] 2020-10-26 13:42
Have nay of you noticed something similar with the PyCharm version? I told a friend about it but it seems to be consuming too much memory as well. We are kind of used to PyCharm chugging memory like there is no tomorrow but this looks weird. Even more when in VSCode I see 90Mb of rum only.

![image](https://user-images.githubusercontent.com/2953658/97179588-48939a00-1799-11eb-9651-d8aacb290bc8.png)

**Comment by RhetTbull** [comment] 2021-01-09 18:03
While sourcery is being much kinder to the CPU, it seems to have recently started hogging memory again.

MacBook Pro, Catalina 10.15.7
Visual Studio Code Version: 1.52.1

I have two separate VS Code windows open and sourcery is using 8GB in one and 10GB in the other

<img width="583" alt="Screen Shot 2021-01-09 at 9 59 57 AM" src="https://user-images.githubusercontent.com/41546558/104105287-e90a3e00-5261-11eb-8211-4aafbebe18c8.png">

**Comment by Hellebore** [comment] 2021-01-11 08:21
Hmm not good. Thanks for reporting - we will look into it.

**Comment by Hellebore** [comment] 2021-01-11 08:49
@RhetTbull Does it slowly ramp up to this value or get there straight away? Do you see any correlation with opening large files/working on large scripts or functions?

**Comment by RhetTbull** [comment] 2021-01-11 14:24
@Hellebore it slowly ramps up (and I tend to leave VS Code opened for days at a time).  I restarted VS Code this morning and sourcery is currently at 2.18 GB memory usage.  I've not noticed any correlation to large scripts. The project I'm currently working on is about 20 KSLOC with a couple of files > 4K lines but I wouldn't call that huge. I do use black to reformat on save (and I'm a habitual saver) so from sourcery's perspective, files may be changing frequently.

**Comment by lmmentel** [comment] 2021-01-12 07:46
I am experiencing the same issue on Linux Mint 20.1

- sourcery 0.8.6
- VSCode 1.52.1
- OS: Linux x64 5.4.0-60-generic

I don't have a screenshot since when sourcery gets memory hungry I need to kill it from the terminal since my system becomes quite unresponsive. There are usually several sourcery processes gulping up all the remaining memory they can find.

**Comment by Hellebore** [comment] 2021-01-13 09:53
Thanks for the info @lmmentel

**Comment by Hellebore** [comment] 2021-01-18 09:32
@RhetTbull @lmmentel We've just released 0.8.7 which should hopefully improve things - could you give it a check and let us know? Thanks!!

**Closed by Hellebore** 2021-01-18 09:32 UTC
Labels: bug

**Comment by RhetTbull** [comment] 2021-01-18 20:11
sourcery 0.8.7 humming along happily at 186MB now!  The fix seems to be working -- thanks!  (VC Code Version: 1.52.1, Mac OS 10.15.7, sourcery 0.8.7)

**Comment by lmmentel** [comment] 2021-06-06 22:52
It seems that there has been some regression since I'm experience the same resource consumption issues that seemed fixed for a time. My current setup is:

- sourcery:  0.9.0
- VSCode: 1.56.2
- OS: Linux mint 20.1 5.4.0-73-generic

![Screenshot from 2021-06-06 19-31-52](https://user-images.githubusercontent.com/8989838/120942634-9195ce80-c72a-11eb-90db-ff8c174690d7.png)
