### ISSUE TITLE
SSL Certificate Failing 

### ISSUE THREAD

**Issue by LP-Codes** [sourcery-ai/sourcery#135] opened 2021-05-10 06:59 UTC
### Issue description or question
Unable to Use With Error -Could not connect to server to authenticate: HTTPSConnectionPool(host='api.sourcery.ai', port=443): Max retries exceeded with url: /access_token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

### Sourcery Version
0.9.0

### Code editor or IDE name and version

Pycharm 
2021.1.1 Community Edition

### OS name and version

Windows

**Comment by LP-Codes** [comment] 2021-06-02 05:36
Hi team , any way to get it fixed

**Comment by LP-Codes** [comment] 2021-06-08 11:58
Hi , just tried I am getting page not found , I am behind corporate proxy it might be the culprit any way to bypass it

**Comment by LP-Codes** [comment] 2021-06-08 12:24
> Hi there - it's a tricky one for us to reproduce and fix I'm afraid. What do you get in your browser when you go to
> 
> https://api.sourcery.ai/health
> 
> on that machine?

Hi , just tried I am getting healthy as response
I am behind corporate proxy it might be the culprit any way to bypass it

**Comment by Astronaut101** [comment] 2021-07-06 06:38
Hello, Sourcery Team!

I am also getting the same SSL error message as the previous user: 

"Could not connect to server to authenticate: HTTPSConnectionPool(host='api.sourcery.ai', port=443): Max retries exceeded with url: /access_token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))"

Being connected to a corporate / work laptop with Zscaler or any other internet security corporate apps might be causing the errors. Is there any workarounds that could be possible to bypass the SSL error message?

**Comment by joshuadavidthomas** [comment] 2021-07-06 18:40
### Issue description or question

+1 for me as well, though my error message is slightly different:

> ```Could not connect to server to authenticate: HTTPSConnectionPool(host='api.sourcery.ai', port=443): Max retries exceeded with url: /access_token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1091)')))```

I have our corporate self signed certificate installed in both Windows and Ubuntu environments. I have attempted to launch VS code using the command ```code --ignore-certificate-errors```. I have changed the ```"http.proxyStrictSSL"``` setting to ```false``` in my settings.json.

Visiting the URL [https://api.sourcery.ai/health](https://api.sourcery.ai/health) shows a healthy response.

### Sourcery Version

0.9.1


### Code editor or IDE name and version

Visual Studio Code v1.57.1


### OS name and version

Windows
Ubuntu 20.04 (via WSL2)

**Comment by bendog** [comment] 2021-08-04 02:57
+1 

Our network has a proxy which does inspections, so it can appear like a MITM attack. We will need a way to turn off the SSL validation :/ 

Sourcery: 0.9.3
Code editor or IDE name and version: PyCharm Pro 2021.2
OS name and version: Windows 10 & Ubuntu 20.04 (via WSL2)

**Comment by brendanator** [comment] 2021-09-15 08:17
Duplicate of #22

**Comment by Hellebore** [comment] 2021-09-15 08:17
Duplicate of #22

**Closed** 2021-09-15 08:17 UTC
Labels: bug, duplicate
